baseURL = 'https://cxd3.dev'
languageCode = 'en'
title = "Cxd3"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = true
    style = "monokai"


[permalinks]
  categories   = "/:slug/"


[taxonomies]
  category = "categories"

[params.categories]
  economy       = ""